Isolate zimcheck testable code in separated file
openzim/zim-tools pull request #153
Opened 2020-08-23 10:35 UTC by MiguelRocha

The current zimcheck class/file structure do not allow for an easy automated testing.

This PR moves the testable code from zimcheck main source file to zimfilecheks making it isolated and therefore testable.

It also adds several unit tests to zimfilechecks.

2020-08-29 16:29 UTC, kelson42 commented
@MiguelRocha I don’t get the purpose of this draft MR. We already have a zimcheck bin! Which ticket is getting fixed with it?

2020-08-30 10:13 UTC, MiguelRocha commented
> @MiguelRocha I don’t get the purpose of this draft MR. We already have a zimcheck bin! Which ticket is getting fixed with it?

The current zimcheck class/file structure do not allow for an easy automated testing (its basically all code inside a single file). What this PR does is just separate the code within different files and makes it testable (with this PR the zimcheck code coverage will jump to 65%). Also, and IMO more importantly we can avoid having regressions by easily introducing unit testing when we have this kind of bugs: https://github.com/openzim/zim-tools/pull/148#issuecomment-674881789

(Sorry for not adding a description in the PR, I'll write a more clean one)

2020-08-30 10:33 UTC, kelson42 commented
@MiguelRocha Thx, makes perfectly sense to me now as well.

2020-09-15 06:18 UTC, kelson42 commented
@MiguelRocha Any chance we could get aPR ready to review for tomorrow?

2020-09-15 18:48 UTC, MiguelRocha commented
@mgautierfr rebased in master and fixed commit history. It pushes code coverage of zim-tools to 31%. Please let me know your comments.

2020-09-21 16:06 UTC, mgautierfr requested changes
This is nice but maybe not enough.
It would be nice to also split this too long `test_articles` into small functions and test them individually (without using a zim file).

But it is a good step and we can split/test more in another PR. I will not block this one for that.

(But we can move the code in subdirectory in this PR)

2020-09-22 18:13 UTC, MiguelRocha commented on src/meson.build
> +executable('zimcheck', 'zimcheck.cpp', 'zimfilechecks.cpp', 'tools.cpp',
Good idea. Done.

2020-09-22 18:16 UTC, MiguelRocha commented
> This is nice but maybe not enough.
> It would be nice to also split this too long `test_articles` into small functions and test them individually (without using a zim file).
> 
> But it is a good step and we can split/test more in another PR. I will not block this one for that.
> 
> (But we can move the code in subdirectory in this PR)

Yes I agree we should split the huge function. Lets do it on other PR.

I've moved the code to a zimcheck directory. If its good I think we can merge.

2020-09-23 10:32 UTC, kelson42 commented
@MiguelRocha Can you please rebase (again) on `master`?

2020-09-23 15:29 UTC, MiguelRocha commented
@kelson42 @mgautierfr rebased into master.

2020-09-23 15:35 UTC, mgautierfr approved these changes

2020-09-23 15:44 UTC, merged