Remove arg zimsplit
openzim/zim-tools pull request #163
Opened 2020-10-03 13:10 UTC by MiguelRocha

This PR adds docopt command line parsing to zimsplit and removes the need for arg.h.

2020-10-05 10:13 UTC, mgautierfr requested changes
Code is good.
However, prefix and size arguments are mandatory. We were not ensuring that is previous version but if we change argument parsing it may be good to refuse empty `prefix` or `size`.
Or use useful default values (prefix=input_zim_file and size=2Gb).

2020-10-07 06:58 UTC, veloman-yunkan approved these changes

2020-10-18 13:30 UTC, MiguelRocha commented
@mgautierfr I added a default prefix and for the size I turned it mandatory.

2020-10-20 14:22 UTC, mgautierfr requested changes
I think after all that we should have a default value for the size (2GB).
We used to split zim using this size when we were using simple cut tool.
And the size as to be specified in Bytes (2*1024*1024*1024=2147483648), this is inconvenient enough to provide a default value.

2020-10-20 14:22 UTC, mgautierfr commented on src/zimsplit.cpp
> +    std::string prefix = PARTPREFIX;
I would use the file input as default prefix.
This way, a `zimsplit foo.zim` will generate `foo.zimaa`, `foo.zimab`, ...

2020-10-28 15:50 UTC, mgautierfr commented on src/zimsplit.cpp
> +	size = args["--size"].asLong();
Use space not tab.

2020-10-28 15:51 UTC, mgautierfr approved these changes

2020-10-28 15:52 UTC, mgautierfr commented
I'm ok with the PR.
As for #169 I'm waiting for the CI to be ok to be sure.

There is this cosmetic issue with the tab. You may want to fix while we are waiting but I will not block for this.

2020-10-30 13:21 UTC, kelson42 commented on src/zimsplit.cpp
> +	size = args["--size"].asLong();
done

2020-10-30 13:24 UTC, kelson42 commented on src/zimsplit.cpp
> +	size = args["--size"].asLong();
done

2020-10-30 13:29 UTC, merged