Optimization of isExternalUrl() and friends
openzim/zim-tools pull request #179
Opened 2020-11-01 10:06 UTC by veloman-yunkan

It turned out that `isExternalUrl()` is a real bottleneck in `zimcheck` - in a `zimcheck -b -A wikipedia_hy_all_mini_2020-08.zim` benchmark it is responsible for about 30% of the total runtime.

2020-11-01 10:34 UTC, veloman-yunkan commented
@kelson42 This is not yet ready for review. I am going to do a couple of more optimizations.

2020-11-01 10:35 UTC, kelson42 commented
My bad, soory, missed the draft.

2020-11-17 14:48 UTC, kelson42 commented
Rebased

2020-11-18 11:04 UTC, mgautierfr requested changes
You definitively not simplify my work here. You go through "complex" `specialUriSchemeKind` with extra arguments and you simplify every things in the last commits.

In this case, I would have prefer to directly have the final function (for both `specialUriSchemeKind` and `isExternalUrl`) instead of doing unnecessary review of outdated code. I wrote a lot of comments I simply delete at the end because they was outdated.

To finish, I think we can make `html_link` a real class :
- Add a constructor.
- Put `isExternalUrl` and `isInternallUrl` as method of `html_link` instead of keeping them as free function.
- Move `uriKind` as a static method.

2020-11-19 09:17 UTC, veloman-yunkan commented on src/tools.cpp
> +    INVALID         // not a valid URI (though it can be a valid relative
Done

2020-11-19 09:19 UTC, veloman-yunkan commented on src/tools.cpp
> +    for ( int i = 0; i <= n ; ++i ) {
Done using `std::map`

2020-11-19 09:21 UTC, veloman-yunkan commented
@mgautierfr The review comments are fixed in new commits (see the last 4 commits in the rebased branch).

2020-11-27 10:56 UTC, kelson42 commented
@mgautierfr This has been rebased against latest master. Can you please follow-up with the review?

2020-12-02 15:55 UTC, mgautierfr commented
I haven't re-review the git history but I agree with the final change.

2020-12-02 15:57 UTC, kelson42 commented
@mgautierfr @veloman-yunkan Then one of you needs to rebase and merge please.

2020-12-02 16:22 UTC, mgautierfr approved these changes

2020-12-02 16:22 UTC, mgautierfr commented
> Then one of you needs to rebase and merge please.

Done.

2020-12-02 16:22 UTC, merged