Add --noindex option to zimrecreate tool
openzim/zim-tools pull request #234
Opened 2021-04-17 23:17 UTC by data-man

2021-04-18 07:26 UTC, data-man commented
BTW, `zim::writer::Creator` extracts some Xapian's data to tmp-files even if indexing parameter == false.

2021-04-19 09:22 UTC, mgautierfr commented
The option should be named "--noftindex".
It deactivate only the fulltext index, the title index (used for suggestion) is always created.

2021-04-19 09:32 UTC, data-man commented
> The option should be named "--noftindex".

Ok.

`do not create a full text index` is the right description?

2021-04-19 10:01 UTC, data-man commented
> the title index (used for suggestion) is always created.

How disable it?
I'm currently using `libzim` with `with_xapian=false` option for this.

2021-04-19 19:48 UTC, kelson42 commented
@data-man @mgautierfr Should be like for `zimwriterfs`:
```
-j, --withoutFTIndex	don't create and add a fulltext index of the content to the ZIM.
```

2021-04-19 20:25 UTC, data-man commented
> -j, --withoutFTIndex

Done.

2021-04-21 13:30 UTC, mgautierfr requested changes

2021-04-21 13:30 UTC, mgautierfr commented on src/zimrecreate.cpp
> +    bool noftindexFlag = false;
Please avoid negative boolean.
Use `withFtIndexFlag`.

2021-04-21 13:32 UTC, mgautierfr commented
> > the title index (used for suggestion) is always created.
>
> How disable it?
> I'm currently using libzim with with_xapian=false option for this.

There is no way to do it for now.

2021-04-21 14:39 UTC, mgautierfr commented
Please squash all your commits into one and we are good.

2021-04-21 14:50 UTC, data-man commented
![github-close-pull-request-with-squash](https://user-images.githubusercontent.com/1754269/115574071-bea53380-a2da-11eb-9e40-c3d181c4a801.png)

No? :)

2021-04-21 15:02 UTC, kelson42 commented
@data-man One commit in a merge commit != One commit without merge commit

2021-04-21 15:03 UTC, mgautierfr commented
We don't squash the Pull request itself into master.
We always create a merge commit to clearly identify which commits are part of the PR.
There is no option in github to squash all commits in the PR into one but still create a merge commit.

2021-04-21 15:36 UTC, data-man commented
I hate git. :(

2021-04-21 15:40 UTC, mgautierfr approved these changes

2021-04-21 15:47 UTC, mgautierfr commented
I've tried to be smart and rebase your branch on top of the new master (after the merge of #237) and git was smarter than me.
I messed a bit with the history and github didn't detect the merge.
But it is merged and in master. I'm closing the PR.

2021-04-21 15:47 UTC, closed without merging

2021-04-21 15:59 UTC, data-man commented
Thanks!

BTW What if use `docopt` also in zimrecreate?

2021-04-21 16:23 UTC, mgautierfr commented
> BTW What if use docopt also in zimrecreate?

Would be a good thing. I haven't mention it as it is not part of this PR. But if you want to change this you are welcomed.

2021-04-21 16:25 UTC, data-man commented
> But if you want to change this you are welcomed.

Ok, I'll do!