Added checks for description and longDescription length.
openzim/zim-tools pull request #333
Opened 2023-03-08 09:49 UTC by Onyx2406

fixes #332

2023-03-08 16:15 UTC, kelson42 commented
@Onyx2406 In case this is not clear, you don't have implemented everything requested.

2023-03-18 17:39 UTC, Onyx2406 commented
can you review this now? @kelson42 

I made some commits

2023-03-19 15:15 UTC, Onyx2406 commented
Done @kelson42

2023-03-19 15:19 UTC, kelson42 approved these changes
LGTM, requesting @veloman-yunkan for a more technical review.

2023-03-20 13:24 UTC, veloman-yunkan requested changes
Please squash all commits into one.

2023-03-20 15:40 UTC, kelson42 commented on src/zimwriterfs/zimwriterfs.cpp
> +  }
Sounds a smart idea, at least as warning.

2023-03-20 15:47 UTC, Onyx2406 commented on src/zimwriterfs/zimwriterfs.cpp
> +  }
should I implement this?

2023-03-20 15:49 UTC, Onyx2406 commented on src/zimwriterfs/zimwriterfs.cpp
> +  }
> should I implement this?

if it is shorter, then what should I print? and what should it do?

2023-03-20 15:53 UTC, Onyx2406 commented on src/zimwriterfs/zimwriterfs.cpp
> +         {"longDescription", required_argument, 0, 'L'},
can you tell how can I fix this? Do I just remove line 195 or it should be no_argument?

2023-03-20 16:04 UTC, veloman-yunkan commented on src/zimwriterfs/zimwriterfs.cpp
> +         {"longDescription", required_argument, 0, 'L'},
Oops, I misinterpreted the meaning of `required_argument`. Nothing to fix here.

2023-03-21 05:52 UTC, kelson42 commented on src/zimwriterfs/zimwriterfs.cpp
> +  }
Yes, take initiative

2023-03-21 06:21 UTC, Onyx2406 commented
Done @kelson42 , can you review?

2023-03-21 06:29 UTC, kelson42 commented
@Onyx2406 I have already approved, @veloman-yunkan is your reviewer now. You don't need to put a comment, just click on the review rerequesting icon.

2023-03-21 12:55 UTC, veloman-yunkan requested changes
The commit description must be edited

2023-03-21 12:55 UTC, veloman-yunkan commented on src/zimwriterfs/zimwriterfs.cpp
>  }
Such functions usually return `false` when the check fails.

2023-03-21 12:55 UTC, veloman-yunkan commented on src/zimwriterfs/zimwriterfs.cpp
> +  }
1. This (except the call to `exit()` can be moved inside the `checkDescriptionLengths()` function
2. Please also add a check on description being non-empty (that will fix #336).

2023-03-21 17:06 UTC, veloman-yunkan requested changes
Code is good. However the commit message body contains some text that has little to no value. Once the commit message is fixed this PR can be merged.

Note that [std::string::length()](https://en.cppreference.com/w/cpp/string/basic_string/length) returns the size of the string in bytes rather than in characters, i.e. the checks will not work correctly on non-ascii texts. But that can be fixed in s separate PR.

2023-03-21 17:18 UTC, Onyx2406 commented
> Code is good. However the commit message body contains some text that has little to no value. Once the commit message is fixed this PR can be merged.
> 
> Note that [std::string::length()](https://en.cppreference.com/w/cpp/string/basic_string/length) returns the size of the string in bytes rather than in characters, i.e. the checks will not work correctly on non-ascii texts. But that can be fixed in s separate PR.

Hi, which commit message body? Can you maybe give reference.

2023-03-21 19:51 UTC, veloman-yunkan reviewed
The title of the commit message is too long - it exceeds the recommended limit, hence part of the title is moved into the body. If you want to mention the new checks in the title, you better split your changes into two commits:

1. Introduce the checks on `--description` option
2. Add `--longDescription` option (along with its own checks, but the latter part doesn't need to be in the commit title)

2023-03-22 09:38 UTC, Onyx2406 commented
> The title of the commit message is too long - it exceeds the recommended limit, hence part of the title is moved into the body. If you want to mention the new checks in the title, you better split your changes into two commits:
> 
> 1. Introduce the checks on `--description` option
> 2. Add `--longDescription` option (along with its own checks, but the latter part doesn't need to be in the commit title)

Looks good now..

2023-03-22 09:40 UTC, veloman-yunkan approved these changes

2023-03-22 10:21 UTC, veloman-yunkan commented on src/zimwriterfs/zimwriterfs.cpp
>  }
Missing closing brace

2023-03-22 10:26 UTC, veloman-yunkan commented
> @veloman-yunkan @Onyx2406 Part of the CI does not pass, it seems to me we have a regression here.

Indeed. I missed a missing closing brace during review since I trust the compiler. Looks like @Onyx2406 didn't build the latest code before requesting review.

2023-03-22 10:50 UTC, mgautierfr commented
> @kelson42 BTW, I wonder why the list of CI jobs in this PR is limited to Packages workflows.

This is because the PR is coming from a branch in another repository. And the CI workflow is not run for security reasons.
However, we may have to check the exact status about that and do something to homogenize all CIs.

2023-03-22 14:41 UTC, merged