fix: rewrite illustration to not use regex
openzim/zim-tools pull request #358
Opened 2023-07-01 18:04 UTC by shenlebantongying

fix https://github.com/openzim/zim-tools/issues/352 by not using regex on binary data.

2023-07-09 19:12 UTC, veloman-yunkan requested changes

2023-07-09 19:12 UTC, veloman-yunkan commented on src/metadata_constraints.cpp
> +  if (illustration.length() >= 24) {
Why is this test needed? What's wrong with always (unconditionally) testing the first 8 bytes?

2023-07-09 19:12 UTC, veloman-yunkan commented on src/metadata_constraints.cpp
> +  if (illustration.substr(16, 8) != png48x48) {
`illustration.substr(16, 8)` will throw if `illustration.length() < 16`

2023-08-04 14:39 UTC, kelson42 commented
@shenlebantongying Any news?

2023-11-18 03:53 UTC, closed without merging